[build]
  base = "src/frontend"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NEXT_PUBLIC_API_URL = "https://faithlink-ntgg.onrender.com"
  NEXT_PUBLIC_APP_URL = "https://subtle-semifreddo-ed7b4b.netlify.app"
  NEXTAUTH_URL = "https://subtle-semifreddo-ed7b4b.netlify.app"
  NEXTAUTH_SECRET = "production-secret-key-2024"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "https://faithlink-ntgg.onrender.com/api/:splat"
  status = 200
  force = true
